### ISSUE TITLE
[smart-faces] Create a new combobox component

### ISSUE THREAD

**Issue by admtriggo** [CruxFramework/crux#495]
_From [wes...@triggolabs.com](https://code.google.com/u/114691046055037037756/) on August 27, 2014 14:23:54_

Would be great if were created a new combobox component.

This new combobox must be:
- Friendly to use
- Integrated with a data provider.
- Pageable through buttons or scroll
- Possibility to use any widget to render items

_Original issue: http://code.google.com/p/crux-framework/issues/detail?id=495_

**Comment by admtriggo** [comment]
_From [juli...@cruxframework.org](https://code.google.com/u/108392056359000771618/) on August 27, 2014 10:29:42_

**Labels:** -Type-Defect Type-Enhancement Module-CruxSmartFaces

**Comment by admtriggo** [comment]
_From [samuel@cruxframework.org](https://code.google.com/u/samuel@cruxframework.org/) on February 25, 2015 15:02:40_

**Owner:** samuel@cruxframework.org  
  **Labels:** -Milestone-M14-C4

**Comment by thiagobustamante** [comment]
It is not part of the core repository anymore, please check the smart-faces repo
