### ISSUE TITLE
[Smart-Faces] Create a simple Grid component

### ISSUE THREAD

**Issue by admtriggo** [CruxFramework/crux#497]
_From [juliano....@gmail.com](https://code.google.com/u/116393219782609280255/) on August 27, 2014 15:50:15_

This component must be:
- Only to display data
- Friendly to use
- Integrated with a data provider.

_Original issue: http://code.google.com/p/crux-framework/issues/detail?id=497_

**Comment by admtriggo** [comment]
_From [juli...@cruxframework.org](https://code.google.com/u/108392056359000771618/) on August 27, 2014 11:51:33_

**Owner:** juli...@cruxframework.org  
  **Labels:** Milestone-M14-C4

**Comment by admtriggo** [comment]
_From [juli...@cruxframework.org](https://code.google.com/u/108392056359000771618/) on February 19, 2015 11:03:56_

**Labels:** -Milestone-M14-C4

**Comment by thiagobustamante** [comment]
Duplicated. See Issue #675
