### ISSUE TITLE
Migrate CRUX to GWT 2.7.0

### ISSUE THREAD

**Issue by admtriggo** [CruxFramework/crux#575]
_From [samuel@cruxframework.org](https://code.google.com/u/samuel@cruxframework.org/) on November 20, 2014 16:28:55_

Migrate the code ASAP!!!

_Original issue: http://code.google.com/p/crux-framework/issues/detail?id=575_

**Comment by admtriggo** [comment]
_From [samuel@cruxframework.org](https://code.google.com/u/samuel@cruxframework.org/) on November 20, 2014 10:29:11_

**Status:** Verified  
  **Labels:** -Type-Defect Type-Enhancement

**Comment by admtriggo** [comment]
_From [alexandr...@triggolabs.com](https://code.google.com/u/115876322122119724331/) on November 25, 2014 08:04:44_

**Status:** Fixed

**Comment by admtriggo** [comment]
_From [alexandr...@triggolabs.com](https://code.google.com/u/115876322122119724331/) on January 13, 2015 05:35:23_

**Status:** Reopened

**Comment by admtriggo** [comment]
_From [juli...@cruxframework.org](https://code.google.com/u/108392056359000771618/) on February 19, 2015 05:10:55_

**Labels:** -Milestone-M14-C5 Milestone-M15-C1

**Comment by admtriggo** [comment]
_From [juli...@cruxframework.org](https://code.google.com/u/108392056359000771618/) on February 19, 2015 05:11:05_

**Labels:** -TargetVersion-5.3.0

**Comment by thiagobustamante** [comment]
Duplicate. See Issue #676
