### ISSUE TITLE
After updating to GWT 2.7 CruxCodeServer is not compiling when .xml files are changed

### ISSUE THREAD

**Issue by admtriggo** [CruxFramework/crux#576]
_From [samuel@cruxframework.org](https://code.google.com/u/samuel@cruxframework.org/) on November 21, 2014 11:11:51_

Let's supose you change some code in a view.xml file. The codeserver is triggered but tell us that no file has changed hence it will not compile the code!

_Original issue: http://code.google.com/p/crux-framework/issues/detail?id=576_

**Comment by admtriggo** [comment]
_From [alexandr...@triggolabs.com](https://code.google.com/u/115876322122119724331/) on November 24, 2014 12:59:38_

**Labels:** -TargetVersion-5.3.0

**Comment by admtriggo** [comment]
_From [juli...@cruxframework.org](https://code.google.com/u/108392056359000771618/) on February 19, 2015 05:21:49_

**Labels:** -Milestone-M14-C4

**Comment by admtriggo** [comment]
_From [samuel@cruxframework.org](https://code.google.com/u/samuel@cruxframework.org/) on February 24, 2015 10:56:57_

**Labels:** -Type-Defect Type-Enhancement

**Comment by thiagobustamante** [comment]
Duplicated issue. See Issue #676
