### ISSUE TITLE
New Value Binding similar to Angular JS binding

### ISSUE THREAD

**Issue by admtriggo** [CruxFramework/crux#589]
_From [thi...@cruxframework.org](https://code.google.com/u/114650528804514463329/) on January 15, 2015 18:49:28_

Purpose of enhancement Would be nice to have a new value binding support similar to angular JS binding, allowing bindings with any widget property and binding expressions.

_Original issue: http://code.google.com/p/crux-framework/issues/detail?id=589_

**Comment by admtriggo** [comment]
_From [alexandr...@triggolabs.com](https://code.google.com/u/115876322122119724331/) on January 29, 2015 09:25:05_

**Owner:** thi...@cruxframework.org

**Comment by admtriggo** [comment]
_From [thi...@cruxframework.org](https://code.google.com/u/114650528804514463329/) on January 30, 2015 10:21:03_

**Status:** Started  
  **Labels:** Milestone-M15-C1

**Comment by thiagobustamante** [comment]
Duplicated Issue. See Issue #675
