### ISSUE TITLE
Update GWT version to 2.7

### ISSUE THREAD

**Issue by samuelcardoso** [CruxFramework/crux#676]
We are facing a problem regarded to SuperDevMode when we try to integrate GWT 2.7 with Crux Framework.

We were able to (almost) fully integrate both, except for some resources that Crux Framework has and unfortunatly are not being detected by Incremental Compilation when we change it.

The problem is: after the first compile everything looks great and we are able to run my application. But if we manually change a View file and invoke the Incremental Compile we receive a message telling that no input files has changed. As we are using Maven project structure in order to fix this we inserted the resources folder (that's where we save our Views files) as a source folder to the project, like:

``` xml
 <source path="public"/>
```

Now the Incremental Compiler understand that it has to compile the code but somehow doesn't compile the Compilation Unit that contains that View resulting in a compilation that doesn't have any of my changes. In order to try to inform that Incremental Compiler has to compile that Compilation Unit we tryed to modify the com.google.gwt.dev.MinimalRebuildCache but all of those methods are private and I cannot access it.

We are still trying to find a workaround to work with it.

**Comment by thiagobustamante** [comment]
We have to change our generators to always access resources as view files, templates etc, through GeneratorContext.getResource() method. It will tell GWT compiler that our generators depends on these files.
